#ifndef lint
static char rcsid[] = "@(#$Id: kio_recoll.cpp,v 1.20 2008-12-01 18:42:52 dockes Exp $ (C) 2005 J.F.Dockes";
#endif
/*
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the
 *   Free Software Foundation, Inc.,
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h> 

#include <string>
using namespace std;

#include <qglobal.h>
#include <qfile.h>
#include <qtextstream.h>
#include <qstring.h>

#include <kdebug.h>
#include <kcomponentdata.h>
#include <kstandarddirs.h>

#include "rclconfig.h"
#include "rcldb.h"
#include "rclinit.h"
#include "pathut.h"
#include "searchdata.h"
#include "rclquery.h"
#include "wasastringtoquery.h"
#include "wasatorcl.h"
#include "kio_recoll.h"
#include "docseqdb.h"
#include "readfile.h"
#include "smallut.h"

using namespace KIO;

RclConfig *RecollProtocol::o_rclconfig;

RclConfig *RclConfig::getMainConfig()
{
    return RecollProtocol::o_rclconfig;
}

RecollProtocol::RecollProtocol(const QByteArray &pool, const QByteArray &app) 
    : SlaveBase("recoll", pool, app), m_initok(false), m_rcldb(0), m_opt("l")
{
    kDebug() << endl;
    if (o_rclconfig == 0) {
	o_rclconfig = recollinit(0, 0, m_reason);
	if (!o_rclconfig || !o_rclconfig->ok()) {
	    m_reason = string("Configuration problem: ") + m_reason;
	    return;
	}
    }
    if (o_rclconfig->getDbDir().empty()) {
	// Note: this will have to be replaced by a call to a
	// configuration building dialog for initial configuration? Or
	// do we assume that the QT GUO is always used for this ?
	m_reason = "No db directory in configuration ??";
	return;
    }

    m_rcldb = new Rcl::Db;
    if (!m_rcldb) {
	m_reason = "Could not build database object. (out of memory ?)";
	return;
    }
    m_pager.setParent(this);
    m_initok = true;
    return;
}

// There should be an object counter somewhere to delete the config when done.
// Doesn't seem needed in the kio context.
RecollProtocol::~RecollProtocol()
{
    kDebug();
    delete m_rcldb;
}

bool RecollProtocol::maybeOpenDb(string &reason)
{
    if (!m_rcldb) {
	reason = "Internal error: initialization error";
	return false;
    }
    if (!m_rcldb->isopen() && !m_rcldb->open(o_rclconfig->getDbDir(), 
					     o_rclconfig->getStopfile(),
					     Rcl::Db::DbRO)) {
	reason = "Could not open database in " + o_rclconfig->getDbDir();
	return false;
    }
    return true;
}

// Not sure this is ever used 
void RecollProtocol::mimetype(const KUrl &url)
{
    kDebug() << url << endl;
    mimeType("text/html");
    finished();
}

bool RecollProtocol::URLToQuery(const KUrl &url, QString& q, QString& opt, 
				int *page)
{
    // "recoll:/some query/" or "recoll:/some query"
    if (url.host().isEmpty()) {
	q = url.path();
	opt = "l";
	if (page)
	    *page = 0;
    } else {
	// Decode the forms' arguments
	q = url.queryItem("q");
	opt = url.queryItem("qtp");
	if (opt.isEmpty()) {
	    opt = "l";
	} 
	if (page) {
	    QString p = url.queryItem("p");
	    if (p.isEmpty()) {
		*page = 0;
	    } else {
		sscanf(p.toAscii(), "%d", page);
	    }
	}
    }
    if (q.startsWith("/"))
	q.remove(0,1);
    if (q.endsWith("/"))
	q.chop(1);
    return true;
}

// This is used by the html interface, but also by the directory one
// when doing file copies for exemple. This is the central dispatcher
// for requests, it has to know a little about both models.
void RecollProtocol::get(const KUrl & url)
{
    kDebug() << url << endl;

    if (!m_initok || !maybeOpenDb(m_reason)) {
	string reason = "Recoll: init error: " + m_reason;
	error(KIO::ERR_SLAVE_DEFINED, reason.c_str());
	return;
    }

    QString host = url.host();
    QString path = url.path();

    int docnum = -1;
    if (host.isEmpty() && 
	(path.isEmpty() || !path.compare("/")||!path.compare("/welcome"))) {
	// recoll:/ : print the html form page
	welcomePage();
	goto out;
    } else if (host.isEmpty() && isRecollResult(url, &docnum)) {
	// Matched an url generated by konqueror out of a directory listing:
	// ie: recoll:/some search string/recollResultxx
	// Redirect to the result document URL
	Rcl::Doc doc;
	if (docnum >= 0 && !m_source.isNull() && m_source->getDoc(docnum, doc)) {
	    mimeType(doc.mimetype.c_str());
	    redirection(KUrl::fromLocalFile((const char *)(doc.url.c_str()+7)));
	    goto out;
	}
    } else if (host.isEmpty() || 
	       (!host.compare("search") && !path.compare("/query"))) {
	// Either "recoll://search/query?query args"
	// Or "recoll:[/]some search string"
	// HTML style query, maybe initial or request for other page
	QString query, opt;
	int page;
	URLToQuery(url, query, opt, &page);
	if (!query.isEmpty()) {
	    htmlDoSearch(query, opt, page);
	    goto out;
	}
    } else if (!host.compare("command")) {
	if (path.indexOf("/QueryDetails") == 0) {
	    queryDetails();
	    goto out;
	} 
    }
    error(KIO::ERR_SLAVE_DEFINED, "Unrecognized URL");
 out:
    finished();
}

// Execute Recoll search, and set the docsource etc.
bool RecollProtocol::doSearch(const QString& q, const QString &qopt)
{
    kDebug() << "query" << q << "opt" << qopt;
    m_srchStr = q;
    m_opt = qopt;
    char opt = qopt.isEmpty() ? 'l' : qopt.toUtf8().at(0);
    string qs = (const char *)q.toUtf8();
    Rcl::SearchData *sd = 0;
    if (opt != 'l') {
	Rcl::SearchDataClause *clp = 0;
	if (opt == 'f') {
	    clp = new Rcl::SearchDataClauseFilename(qs);
	} else {
	    // If there is no white space inside the query, then the user
	    // certainly means it as a phrase.
	    bool isreallyaphrase = false;
	    if (qs.find_first_of(" \t") == string::npos)
		isreallyaphrase = true;
	    clp = isreallyaphrase ? 
		new Rcl::SearchDataClauseDist(Rcl::SCLT_PHRASE, qs, 0) :
		new Rcl::SearchDataClauseSimple(opt == 'o' ?
						Rcl::SCLT_OR : Rcl::SCLT_AND, 
						qs);
	}
	sd = new Rcl::SearchData(Rcl::SCLT_OR);
	if (sd && clp)
	    sd->addClause(clp);
    } else {
	sd = wasaStringToRcl(qs, m_reason);
    }
    if (!sd) {
	m_reason = "Internal Error: cant build search";
	error(KIO::ERR_SLAVE_DEFINED, m_reason.c_str());
	finished();
	return false;
    }

    RefCntr<Rcl::SearchData> sdata(sd);
    sdata->setStemlang("english");
    RefCntr<Rcl::Query>query(new Rcl::Query(m_rcldb));
    if (!query->setQuery(sdata)) {
	m_reason = "Query execute failed. Invalid query or syntax error?";
	error(KIO::ERR_SLAVE_DEFINED, m_reason.c_str());
	finished();
	return false;
    }

    DocSequenceDb *src = 
	new DocSequenceDb(RefCntr<Rcl::Query>(query), "Query results", sdata);
    if (src == 0) {
	error(KIO::ERR_SLAVE_DEFINED, "Can't build result sequence");
	finished();
	return false;
    }
    m_source = RefCntr<DocSequence>(src);
    return true;
}

// Note: KDE_EXPORT is actually needed on Unix when building with
// cmake. Says something like __attribute__(visibility(defautl))
// (cmake apparently sets all symbols to not exported)
extern "C" {KDE_EXPORT int kdemain(int argc, char **argv);}

int kdemain(int argc, char **argv)
{
#ifdef KDE_VERSION_3
    KInstance instance("kio_recoll");
#else
    KComponentData instance("kio_recoll");
#endif
    kDebug() << "*** starting kio_recoll " << endl;

    if (argc != 4)  {
	kDebug() << "Usage: kio_recoll proto dom-socket1 dom-socket2\n" << endl;
	exit(-1);
    }

    RecollProtocol slave(argv[2], argv[3]);
    slave.dispatchLoop();

    kDebug() << "kio_recoll Done" << endl;
    return 0;
}
