// Bogus file to solve the following problem:

// Bison generates y.tab.h and inserts a line in the generated cpp
// file to include it

// However, we tell automake to use wasaparse.cpp and wasaparse.hpp as
// names for the generated files. This does not fix the #include
// y.tab.h line, so it fails.

// This workaround file just includes the appropriate file as
// generated by automake

#include "wasaparse.hpp"
