.\" $Id: recollindex.1,v 1.7 2008-09-05 10:25:54 dockes Exp $ (C) 2005 J.F.Dockes\$
.TH RECOLLINDEX 1 "8 January 2006"
.SH NAME
recollindex \- indexing command for the Recoll full text search system
.SH SYNOPSIS
.B recollindex -h
.br
.B recollindex
[
.B -c
<configdir>
]
[
.B -z
]
[
.B -m
]
[
.B -w
<seconds>
]
[
.B -D
]
[
.B -x
]
.br
.B recollindex 
[
.B -c
<configdir>
]
.B -i 
<filename [filename ...]>
.br
.B recollindex 
[
.B -c
<configdir>
]
.B -e 
<filename [filename ...]>
.br
.B recollindex
[
.B -c
<configdir>
]
.B -l
.br
.B recollindex
[
.B -c
<configdir>
]
.B -s 
<lang>
.br
.B recollindex
[
.B -c
<configdir>
]
.B -S

.SH DESCRIPTION
The
.B recollindex
utility allows you to perform indexing operations for the Recoll text
search system.
.PP
The 
.B -c 
option specifies the configuration directory name, overriding the
default or $RECOLL_CONFDIR.
.PP
There are several modes of operation. 
.PP
The normal mode will index the set of files described in the configuration
file 
.B recoll.conf.
This will incrementally update the database with files that changed since
the last run. If option 
.B -z 
is given, the database will be erased before starting.
.PP
If option 
.B
\-m 
is given, recollindex is started for real time monitoring, using the
file system monitoring package it was configured for (either fam, gamin, or
inotify). This mode must have been explicitly configured when building the
package, it is not available by default. The program will normally detach
from the controlling terminal and become a daemon. If option
.B
\-D 
is given, it will stay in the foreground. Option
.B
\-w 
<seconds> can be used to specify that the program should sleep for the
specified time before indexing begins. The default value is 60. The daemon
normally monitors the X11 session and exits when it is reset.
Option 
.B
\-x
disables this X11 session monitoring (daemon will stay alive even if it
cannot connect to the X11 server).
.PP
.B recollindex -l 
will list the names of available language stemmers.
.PP
The other modes are useful mainly for testing.
.PP
.B recollindex -i
will index individual files into the database. The stem expansion databases
will not be updated.
.PP
.B recollindex -e
will erase data for individual files from the database. The stem expansion
databases will not be updated.
.PP
.B recollindex -s 
will build the stem expansion database for a given language, which may or
may not be part of the list in the configuration file. If the language is
not part of the configuration, the stem expansion database will be deleted
at the end of the next normal indexing run. You can get the list of stemmer
names from the 
.B recollindex -l
command. Note that this is mostly for experimental use, the normal way to
add a stemming language is to set it in the configuration, either by
editing "recoll.conf" or by using the GUI indexing configuration dialog.
.br
At the time of this writing, the following languages
are recognized (out of Xapian's stem.h):
.IP \(bu
danish
.IP \(bu
dutch
.IP \(bu
english Martin Porter's 2002 revision of his stemmer
.IP \(bu
english_lovins Lovin's stemmer
.IP \(bu
english_porter Porter's stemmer as described in his 1980 paper
.IP \(bu
finnish 
.IP \(bu
french 
.IP \(bu
german 
.IP \(bu
italian
.IP \(bu
norwegian
.IP \(bu
portuguese
.IP \(bu
russian
.IP \(bu
spanish
.IP \(bu
swedish
.PP
.B recollindex -S
will rebuild the phonetic/orthographic index. This feature uses the 
.B aspell
package, which must be installed on the system.

.SH SEE ALSO
.PP 
recoll(1) recoll.conf(5)
