.\" $Id: recoll.1,v 1.2 2006-09-08 09:02:47 dockes Exp $ (C) 2005 J.F.Dockes\$
.TH RECOLL 1 "8 January 2006"
.SH NAME
recoll \- user interface for the Recoll full text search system
.SH SYNOPSIS
.B recoll
[
.B -c
<configdir>
]
.SH DESCRIPTION
The
.B recoll
command will start the graphical user interface for querying the 
.B Recoll 
database.
.PP
On the first run, 
.B recoll
will create the user configuration which can be customized
before starting the first indexation.
.PP
The 
.B -c 
option specifies the configuration directory name, overriding the
default or $RECOLL_CONFDIR.
.PP
Please refer to online help for a full description.
.SH SEE ALSO
.PP 
recollindex(1) recoll.conf(5)
