#!/bin/sh
# @(#$Id: rclid3,v 1.3 2008-10-08 08:27:34 dockes Exp $  (C) 2004 J.F.Dockes
#================================================================
# rclid3
# Handle audio files for recoll. This uses id3info to extract tags
#================================================================
# set variables
LANG=C ; export LANG
LC_ALL=C ; export LC_ALL
progname="rclid3"
filetype=audio


#RECFILTCOMMONCODE
##############################################################################
# !! Leave the previous line unmodified!! Code imported from the
# recfiltcommon file

# Utility code common to all shell filters. This could be sourced at run
# time, but it's slightly more efficient to include the code in the
# filters at build time (with a sed script).

# Describe error in a way that can be interpreted by our caller
senderror()
{
    echo RECFILTERROR $*
    # Also alert on stderr just in case
    echo ":2:$progname::: $*" 1>&2
    exit 1
}

iscmd()
{
    cmd=$1
    case $cmd in
    */*)
	if test -x $cmd ; then return 0; else return 1; fi ;;
    *)
      oldifs=$IFS; IFS=":"; set -- $PATH; IFS=$oldifs
      for d in $*;do test -x $d/$cmd && return 0;done
      return 1 ;;
    esac
}

checkcmds()
{
    for cmd in $*;do
      if iscmd $cmd 
      then 
        a=1
      else 
        senderror HELPERNOTFOUND $cmd
      fi
    done
}

# show help message
if test $# -ne 1 -o "$1" = "--help" 
then
  echo "Convert a $filetype file to HTML text for Recoll indexing."
  echo "Usage: $progname [infile]"
  exit 1
fi

infile="$1"

# check the input file existence (may be '-' for stdin)
if test "X$infile" != X- -a ! -f "$infile"
then
  senderror INPUTNOSUCHFILE "$infile"
fi

# protect access to our temp files and directories
umask 77

##############################################################################
# !! Leave the following line unmodified !
#ENDRECFILTCOMMONCODE

checkcmds id3info

# output the result
echo '<html><head>'
#echo '<title>' "$title" '</title>'
echo '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'

nocaptionexp='s/===.*://'

if test X$RECOLL_FILTER_FORPREVIEW = Xyes ; then
echo '</head><body><pre>'
id3info "$infile" | \
   sed -e '/Tag information for/d' \
       -e 's/===[^(]*//' \
       -e 's/</&lt;/g' -e 's/&/&amp;/g' -e 's/"/&quot;/g' -e 's/>/&gt;/g' 
echo '</pre></body></html>'

else
# Indexing. There are many other fields which we could process this way.
# Would also need that some fields are set up in the "fields" config
# file to be really useful
id3info "$infile" | awk -F: \
'{
   value=""
   for (i = 2; i <=NF; i++) {
     value = value " " $i
   }
   sub("&", "&amp;", value)
   sub("\"", "&quot;", value)
   sub("<", "&lt;", value)
   sub(">", "&gt;", value)
}
/TIT2/{
   printf "<meta name=\"title\" content=\"%s\">\n", value
   body=body value "\n"
   next
}
/TPE1/{
   printf "<meta name=\"artist\" content=\"%s\">\n", value
   body=body value "\n"
   next
}
/TALB/{
   printf "<meta name=\"album\" content=\"%s\">\n", value
   body=body value "\n"
   next
}
{
   body=body value "\n"
}
END{print "</head><body><pre>";print body;print "</pre></body></html>"}
'
fi

exit 0
