#!/bin/sh
# @(#$Id: rclman,v 1.1 2007-02-06 15:08:22 dockes Exp $  (C) 2004 J.F.Dockes
# Parts taken from Estraier:
#================================================================
# Estraier: a personal full-text search system
# Copyright (C) 2003-2004 Mikio Hirabayashi
#================================================================
#================================================================
# rclman
# Process a manual page with groff and output html
# We'd like to use -Thtml, but this doesn't seem to be always available.
# So we use -Tutf8 and postprocess this to remove the ^H overstriking
#
#================================================================


# set variables
LANG=C ; export LANG
LC_ALL=C ; export LC_ALL
progname="rclman"
filetype=man



#RECFILTCOMMONCODE
##############################################################################
# !! Leave the previous line unmodified!! Code imported from the
# recfiltcommon file

# Utility code common to all shell filters. This could be sourced at run
# time, but it's slightly more efficient to include the code in the
# filters at build time (with a sed script).

# Describe error in a way that can be interpreted by our caller
senderror()
{
    echo RECFILTERROR $*
    # Also alert on stderr just in case
    echo ":2:$progname::: $*" 1>&2
    exit 1
}

iscmd()
{
    cmd=$1
    case $cmd in
    */*)
	if test -x $cmd ; then return 0; else return 1; fi ;;
    *)
      oldifs=$IFS; IFS=":"; set -- $PATH; IFS=$oldifs
      for d in $*;do test -x $d/$cmd && return 0;done
      return 1 ;;
    esac
}

checkcmds()
{
    for cmd in $*;do
      if iscmd $cmd 
      then 
        a=1
      else 
        senderror HELPERNOTFOUND $cmd
      fi
    done
}

# show help message
if test $# -ne 1 -o "$1" = "--help" 
then
  echo "Convert a $filetype file to HTML text for Recoll indexing."
  echo "Usage: $progname [infile]"
  exit 1
fi

infile="$1"

# check the input file existence (may be '-' for stdin)
if test "X$infile" != X- -a ! -f "$infile"
then
  senderror INPUTNOSUCHFILE "$infile"
fi

##############################################################################
# !! Leave the following line unmodified !
#ENDRECFILTCOMMONCODE

checkcmds groff sed awk iconv

# The strange 'BEGIN' setup is to prevent 'file' from thinking this file
# is an awk program
groff -man -Tutf8 < "$infile" | sed -e 's/.//g' -e 's/.//g' |\
awk 'BEGIN'\
' {
  print "<html><head><title></title>"
  print "<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">"
  print "</head>\n<body>\n<p>"
}
{
  gsub(/&/, "\\&amp;", $0)
  gsub(/</, "\\&lt;", $0)
  gsub(/>/, "\\&gt;", $0)

  print $0 "<br>"
}
END {
    print "</p></body></html>"
}' | iconv -f UTF-8 -t UTF-8 -c -s 

# exit normally
exit 0
