#!/bin/sh
# @(#$Id: rclxls,v 1.2 2006-11-20 15:28:30 dockes Exp $  (C) 2004 J.F.Dockes
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

#================================================================
# rclppt
# Handle excel files for recoll. 
# Uses xls2csv from the catdoc utilities
# (http://ftp.45.free.net/~vitus/software/catdoc/)
# Note: xls2csv is supposed to detect the source charset from the excel
# file but this does not always work. If you see unexpected russian chars
# (the russian author's default charset) in the output, you may want to add
# ie a -s 8859-1 option to the xls2csv command line.
#================================================================
# set variables
LANG=C ; export LANG
LC_ALL=C ; export LC_ALL
progname="rclxls"

# show help message
if test $# -ne 1 -o "$1" = "--help" 
then
  printf 'Process an excel file for recoll indexation.\n'
  printf 'Usage: %s [infile]\n' "$progname"
  exit 1
fi

infile="$1"

iscmd()
{
    cmd=$1
    case $cmd in
    */*)
	if test -x $cmd ; then return 0; else return 1; fi ;;
    *)
      oldifs=$IFS; IFS=":"; set -- $PATH; IFS=$oldifs
      for d in $*;do test -x $d/$cmd && return 0;done
      return 1 ;;
    esac
}
checkcmds()
{
    cmdsok=0
    for cmd in $*;do
      if iscmd $cmd 
      then 
        cmdsok=1
      else 
        cmdsok=0
      fi
    done
}

# check the input file existence
if test ! -f "$infile"
then
  printf '%s: %s: no such file\n' "$progname" "$infile"
  exit 1
fi
checkcmds xls2csv
if test X$cmdsok = X0 ; then
   printf "xls2csv not found"
   exit 1
fi

# output the result
echo '<html><head>'
#echo '<title>' "$title" '</title>'
echo '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">'
echo '</head><body>'
echo '<pre>'

xls2csv -c'	' -b"<hr>" -d utf-8 "$infile" | \
   sed -e 's/</&lt;/g' -e 's/&/&amp;/g' 

echo '</pre>'
echo '</body></html>'

# exit normally
exit 0
